### ISSUE TITLE
ATAC-seq application?

### ISSUE THREAD

**Issue by grandrews** [jvierstra/footprint-tools#11]
Not an issue per se, but could your method be used to calculate expected cleavages for ATAC-seq data? (after obviously shifting the reads +4 bp and -5 bp for plus and minus strand reads respectively)

**Comment by jvierstra** [comment]
In principle, one could compute the expected cleavages for Tn5 data, however, 6mer sequence preference model should be trained on a Tn5 experiment from de-proteinized DNA (naked DNA). Another issue also is that the sequence preference of Tn5 is ~8-9 bp resulting in a large model  of ~65K parameters which might not perform well. In any case, I can help you implement this if you like.
