### ISSUE TITLE
Compilation fails due to k-d tree code missing from current master

### ISSUE THREAD

**Issue by alexpreynolds** [jvierstra/footprint-tools#2]
K-d tree code and references to it in `setup.py` are in commit 6e34bd67c638948dda8a55976b92a2699828eafc (https://github.com/jvierstra/footprint-tools/tree/6e34bd67c638948dda8a55976b92a2699828eafc) but are not in the latest commit in the master branch. 

As a result, when building off the master branch, compilation will fail on `footprint_tools/stats/mutual_information.h` not finding the `kdtree.h` header and related library.

**Comment by jvierstra** [comment]
Should be fixed -- I removed all the dependencies to this code.
