### ISSUE TITLE
what should I use for interval.bed file?

### ISSUE THREAD

**Issue by shintarok111** [jvierstra/footprint-tools#23]
I am trying to create a dispersion model with my data. 
I've read the documentation but couldn't find specific information about the interval.bed file. Does this file represent the BED file containing the lengths of each chromosome, or does it refer to a hotspot or peak.bed file that is generated by hotspot2?

Thank you for your kind assistance.

**Comment by jvierstra** [comment]
The interval file is a file of the genome regions that defines where you would like to identify footprints. Typically we use the peaks from a peak caller (hotspot2; https://github.com/Altius/hotspot2, or other).

**Comment by shintarok111** [comment]
Thank you for your reply!
