### ISSUE TITLE
Step 3a: Create a sequence preference model

### ISSUE THREAD

**Issue by shubihu** [jvierstra/footprint-tools#5]
Hi, I got an not found error  in step3a with the commad  
wget http://hgdownload.cse.ucsc.edu/goldenpath/hg38/encodeDCC/wgEncodeMapability/wgEncodeCrgMapabilityAlign36mer.bigWig
and I can not acces the http address in the InternetExplorer.

**Comment by jvierstra** [comment]
The model was generated using hg19. The mappability file for that genome is found here: http://hgdownload.cse.ucsc.edu/goldenpath/hg19/encodeDCC/wgEncodeMapability/wgEncodeCrgMapabilityAlign36mer.bigWig

I updated the documentation to reflect that.
