### ISSUE TITLE
Trouble accessing posterior probabilities

### ISSUE THREAD

**Issue by grandrews** [jvierstra/footprint-tools#9]
Hi! Greatly enjoyed your footprinting paper in Nature this past year! I am trying to look at footprints over specific genomic intervals. I am following your tutorial [https://footprint-tools.readthedocs.io/en/latest/examples/plot.html](url).
But I am receiving the error "OSError: file `https://resources.altius.org/~jvierstra/projects/footprinting.2020/posteriors/posteriors.per-nt.bed.gz` not found" when loading in the posterior probabilities. I also run into a similar problem when trying to download the file directly from your companion site to the paper (You don't have permission to access /~jvierstra/projects/footprinting.2020/posteriors/posteriors.per-nt.bed.gz on this server.) Thanks so much in advance for the help!
-Greg

**Comment by jvierstra** [comment]
Greg,

We had an issue with the file system on our server. I believe this has now been fixed. Try it again and see if it works now.

**Comment by grandrews** [comment]
Thanks so much for your swift reply, I can confirm it works now!
